### ISSUE TITLE
Error Installing v24.0.0

### ISSUE THREAD

**Issue by nick-w-nick** [dgraph-io/dgraph-js#231]
I have been trying to debug an error we've been hitting since upgrading to `dgraph-js` `v24.0.0`, and noticed that it happens in this repo as well.

This error seems to be related to the `grpc` package, as shown in the logs below:
```
npm WARN deprecated grpc@1.24.11: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.
npm ERR! code 1
npm ERR! path /Users/user/Documents/GitHub/dgraph-js/node_modules/grpc
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! Failed to execute '/Users/user/.nvm/versions/node/v18.18.0/bin/node /Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/src/node/extension_binary/node-v108-darwin-arm64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/src/node/extension_binary/node-v108-darwin-arm64-unknown --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.18.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/src/node/extension_binary/node-v108-darwin-arm64-unknown/grpc_node.node" (not found)
npm ERR! node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.24.11/node-v108-darwin-arm64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://node-precompiled-binaries.grpc.io/grpc/v1.24.11/node-v108-darwin-arm64-unknown.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for grpc@1.24.11 and node@18.18.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://node-precompiled-binaries.grpc.io/grpc/v1.24.11/node-v108-darwin-arm64-unknown.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.12.5 found at "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/user/Library/Caches/node-gyp/18.18.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/user/Library/Caches/node-gyp/18.18.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/user/Library/Caches/node-gyp/18.18.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Darwin 23.6.0
npm ERR! gyp ERR! command "/Users/user/.nvm/versions/node/v18.18.0/bin/node" "/Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/src/node/extension_binary/node-v108-darwin-arm64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/src/node/extension_binary/node-v108-darwin-arm64-unknown" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /Users/user/Documents/GitHub/dgraph-js/node_modules/grpc
npm ERR! gyp ERR! node -v v18.18.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/user/.nvm/versions/node/v18.18.0/bin/node /Users/user/.nvm/versions/node/v18.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/src/node/extension_binary/node-v108-darwin-arm64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/user/Documents/GitHub/dgraph-js/node_modules/grpc/src/node/extension_binary/node-v108-darwin-arm64-unknown --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/user/Documents/GitHub/dgraph-js/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm ERR! node-pre-gyp ERR! System Darwin 23.6.0
npm ERR! node-pre-gyp ERR! command "/Users/user/.nvm/versions/node/v18.18.0/bin/node" "/Users/user/Documents/GitHub/dgraph-js/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
npm ERR! node-pre-gyp ERR! cwd /Users/user/Documents/GitHub/dgraph-js/node_modules/grpc
npm ERR! node-pre-gyp ERR! node -v v18.18.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok
```

I have tried with all node versions from v16 all the way up to v22 with the same error each time. It seems to be related to some of the hosted binaries on `grpc.io` not being accessible. This is evident by these lines in the above console output:
```
npm ERR! node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.24.11/node-v108-darwin-arm64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://node-precompiled-binaries.grpc.io/grpc/v1.24.11/node-v108-darwin-arm64-unknown.tar.gz 
```

For reference, this error is not present on the previous `dgraph-js` version, `v21.03.0`.

**Comment by nick-w-nick** [comment]
@shivaji-kharse @ryanfoxtyler I noticed that my PR #233 to fix the issue got merged, but a release still hasn't been created. Please let us know when we can expect a new version to be published to remediate this issue.

Thanks!

**Comment by mangalaman93** [comment]
[v24.1.0](https://www.npmjs.com/package/dgraph-js/v/24.1.0)  is released. Let us know if you face any issues. Thanks
